#!/bin/bash
PATH=/opt/someApp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

## backup
# en crontab -e add to run every day at 23:59
# m h  dom mon dow   command
# 59 23 * * * cd $HOME/kamaoo;./mkbackup

cd $HOME/kamaoo
echo "creating backup ...wait ..."
fecha=$(date +"%Y-%m-%d.%H:%M")

cp "lita_chat.log" "lita_chat.log.tmp"
rm "lita_chat.log"

mkdir "logs/$fecha"
touch "logs/$fecha/log"
echo "--- kamaoo ver 0.01b ---
repo at: https://github.com/leprechuanese/kamaoo
$fecha" >> "logs/$fecha/log"

echo "...creating words.$fecha.png"
./solo_palabras "lita_chat.log.tmp"  > data-log

tmp2="--- Most frecuent words (Total Unique Count: $(awk -F '\t' '{print $1}' data-log | sort | uniq -c | sort -nr | wc -w)) ---"
tmp3="$(awk -F '\t' '{print $1}' data-log | sort | uniq -c | sort -nr)"

python crea_grafica-colored.py
tmp=$(curl -F c=@fn-worldcloud-color.png https://ptpb.pw)

echo "--- words.$fecha.png ---" >> "logs/$fecha/log"
echo "$tmp" >> "logs/$fecha/log"
echo >> "logs/$fecha/log"

mv fn-worldcloud-color.png "logs/$fecha/words.$fecha.png"

echo "...creating users.$fecha.png"

./solo_users "lita_chat.log.tmp"  > data-log
python crea_grafica-colored.py
tmp=$(curl -F c=@fn-worldcloud-color.png https://ptpb.pw)

echo "--- users.$fecha.png ---" >> "logs/$fecha/log"
echo "$tmp" >> "logs/$fecha/log"
echo >> "logs/$fecha/log"
mv fn-worldcloud-color.png "logs/$fecha/users.$fecha.png"

tmp4="--- User Count: $(awk -F '\t' '{print $1}' data-log | sort | uniq -c | sort -nr | wc -w) ---"
tmp4="$tmp4 Places: $(awk -F '\t' '{print $1}' data-log | sort | uniq -c | sort -nr | head -3 | awk '{print $2}')"

tmp5="$(awk -F '\t' '{print $1}' data-log | sort | uniq -c | sort -nr)"

num=1
for i in $(awk -F '\t' '{print $1}' data-log | sort | uniq -c | sort -nr | head -3 | awk '{print $2}'); do
	echo "Creating $num-place.$i.$fecha.png"
	./solo_palabras "lita_chat.log.tmp" "$i" > data-log
	python crea_grafica-colored.py
	tmp=$(curl -F c=@fn-worldcloud-color.png https://ptpb.pw)
	echo "--- $num-place.$i.$fecha ---" >> "logs/$fecha/log"
	echo "$tmp" >> "logs/$fecha/log"
	echo >> "logs/$fecha/log"
	mv fn-worldcloud-color.png "logs/$fecha/$num-place.$i.$fecha.png"
	let num=num+1
done

echo "$tmp2" >> "logs/$fecha/log"
echo "$tmp4" >> "logs/$fecha/log"
echo "--- Words ---" >> "logs/$fecha/log"
echo "$tmp3" >> "logs/$fecha/log"
echo "--- Users ---" >> "logs/$fecha/log"
echo "$tmp5" >> "logs/$fecha/log"

cp lita_chat.log "logs/$fecha/lita_chat.log"

echo "compressing folder ..."
tar -zcvf $HOME/kamaoo/logs/$fecha.tar.gz $HOME/kamaoo/logs/$fecha

echo "cleaning up ..."
rm -rf "logs/$fecha"
cp lita_chat.log.tmp lita_chat.log.bk
rm lita_chat.log.tmp
rm data-log

echo "Done!";echo
