#!/bin/bash

# crea activo canal del log
in="$1"
canal="$2"
if [ ! -f "$in" ]; then
	echo "File not found! '$in'"
	echo 'Usage: $0 "<archivo_log>" "<canal>"'
	exit
fi
echo 
while IFS= read -r line; do
	words=$(echo "$line" | grep "$canal" | awk '{print $6}')
	if [ ${words//[,:.\"\[]} ]; then
		echo -n "${words//[,:.\"\[\]]} "
	fi
done < "$in"
echo;echo
