#!/bin/bash

# crea solo palabras del log
in="$1"
canal="$2"
#filtro='[,:.\"\}\^\=\#\*\/\\]'
filtro='[,]'
min_len=2
if [ ! -f "$in" ]; then
	echo "File not found! '$in'"
	echo "Usage: $0 <archivo_log>"
	exit
fi
echo 
while IFS= read -r line; do
	words=$(echo "$line" | grep "$canal" | awk '{$1=$2=$3=$4=$5=$6=""; print $0}')
	words=${words//$filtro}
	
	for i in $words; do
		i="${i/ /}"
		if [[ "${#i}" -gt "$min_len" ]]; then
			echo "$i"
		fi
	done
done < "$in"
echo;echo
